CREATE TABLE tenants
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT NOT NULL,
    property_id         BIGINT,
    lease_start_date    DATE,
    lease_end_date      DATE,
    rent_amount         DECIMAL(10,2),
    rent_due_day        INT,

    created_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          BIGINT,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_by          BIGINT,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    status              VARCHAR(255),

    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uk_tenants_user_id UNIQUE (user_id)
);